Demo.Web/Areas/Admin/Models/AddBookModel.cs
namespace Demo.Web.Areas.Admin.Models
{
    public class AddBookModel
    {
        public string Title { get; set; }
        public Guid AuthorId { get; set; }
        public DateTime PublishDate { get; set; }
    }
}

Demo.Web/Areas/Admin/Models/DashboardIndexModel.cs
namespace Demo.Areas.Admin.Models
{
    public class DashboardIndexModel
    {
    }
}

Demo.Web/Models/Demo/IndexModel.cs
namespace Demo.Web.Models.Demo
{
    public class IndexModel
    {
        public string Email { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
    }
}

Demo.Web/Models/ErrorViewModel.cs
namespace Demo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Demo.Web/Models/IItem.cs
namespace Demo.Models
{
    public interface IItem
    {
        double GetAmount();
    }
}

Demo.Web/Models/IProduct.cs
namespace Demo.Models
{
    public interface IProduct
    {
        double GetPrice();
    }
}

Demo.Web/Models/Item.cs
namespace Demo.Models
{
    public class Item : IItem
    {
        public double GetAmount()
        {
            return 500;
        }
    }
}

Demo.Web/Models/Product1.cs
namespace Demo.Models
{
    public class Product1 : IProduct
    {
        public double GetPrice()
        {
            return 100;
        }
    }
}

Demo.Web/Models/Product2.cs
namespace Demo.Models
{
    public class Product2 : IProduct
    {
        public double GetPrice()
        {
            return 200;
        }
    }
}

Demo.Web/Areas/Admin/Controllers/BooksController.cs
using Demo.Domain.Services;
using Demo.Domain.Entities;
using Demo.Web.Areas.Admin.Models;
using Microsoft.AspNetCore.Mvc;


namespace Demo.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BooksController : Controller
    {
       private readonly IBookService _bookService;
        public BooksController(IBookService bookService)
        {
            _bookService=bookService;         
        }
        public IActionResult Index()
        {         
            return View();
        }
        public IActionResult Add()
        {
            var model = new AddBookModel();
            return View();
        }
        [HttpPost,ValidateAntiForgeryToken]
        public IActionResult Add(AddBookModel model)
        {
            if (ModelState.IsValid)
            {
                _bookService.AddBook(new Book { Title = model.Title});
            }
            
            return View();
        }

        public IActionResult Edit()
        {
            return View();
        }
    }
}

Demo.Web/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace Demo.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Demo.Web/Controllers/DemoController.cs
using Demo.Web.Models.Demo;
using Microsoft.AspNetCore.Mvc;

namespace Demo.Controllers
{
    public class DemoController : Controller
    {
        public IActionResult Index()
        {
            var model = new IndexModel();

            return View(model);
        }

        [HttpPost]
        public IActionResult Index(IndexModel model)
        {
            return View(model);
        }
    }
}

Demo.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Demo.Models;
using Microsoft.AspNetCore.Mvc;

namespace Demo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IItem _item;
        private readonly IProduct _product;

        public HomeController(ILogger<HomeController> logger, IItem item, [FromKeyedServices("Config1")] IProduct product)
        {
            _logger = logger;
            _item = item;
            _product = product;
        }

        public IActionResult Index()
        {
            var amount = _item.GetAmount();
            var price = _product.GetPrice();
            _logger.LogInformation("I am in index page.");
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Demo.Web/Areas/Admin/Views/Books/Add.cshtml
@model AddBookModel
@{
    ViewData["Title"] = "Add Book";
}

<!--begin::App Content Header-->
<div class="app-content-header">
    <!--begin::Container-->
    <div class="container-fluid">
        <!--begin::Row-->
        <div class="row">
            <div class="col-sm-6"><h3 class="mb-0">Add Book</h3></div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-end">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Add Book</li>
                </ol>
            </div>
        </div>
        <!--end::Row-->
    </div>
    <!--end::Container-->
</div>
<!--end::App Content Header-->
<!--begin::App Content-->
<div class="app-content">
    <!--begin::Container-->
    <div class="container-fluid">
        <!--begin::Row-->
        <div class="row g-4">
            <!--begin::Col-->
            <div class="col-12">
                <div class="callout callout-info">
                    For detailed documentation of Form visit
                    <a href="https://getbootstrap.com/docs/5.3/forms/overview/"
                       target="_blank"
                       rel="noopener noreferrer"
                       class="callout-link">
                        Bootstrap Form
                    </a>
                </div>
            </div>
            <!--end::Col-->
            <!--begin::Col-->
            <div class="col-md-6">
                <!--begin::Quick Example-->
                <div class="card card-primary card-outline mb-4">
                    <!--begin::Header-->
                    <div class="card-header"><div class="card-title">Add a new book</div></div>
                    <!--end::Header-->
                    <!--begin::Form-->
                    <form asp-antiforgery="true" asp-area="Admin" asp-controller="Books"
                          asp-action="Add" method="post">
                        <!--begin::Body-->
                        <div class="card-body">
                            <div class="mb-3">
                                <label asp-for="Title" class="form-label">Book Title</label>
                                <input type="text"
                                       class="form-control"
                                       asp-for="Title"
                                       aria-describedby="titleHelp" />
                                <div id="titleHelp" class="form-text">
                                    Provide a friendly title
                                </div>
                            </div>
                            <div class="mb-3">
                                <label asp-for="AuthorId" class="form-label">Author</label>
                                <input type="text" class="form-control" asp-for="AuthorId" />
                            </div>
                        </div>
                        <!--end::Body-->
                        <!--begin::Footer-->
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                        <!--end::Footer-->
                    </form>
                    <!--end::Form-->
                </div>
                <!--end::Quick Example-->
            </div>
            <!--end::Col-->
        </div>
        <!--end::Row-->
    </div>
    <!--end::Container-->
</div>
<!--end::App Content-->

Demo.Web/Areas/Admin/Views/Books/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

Demo.Web/Areas/Admin/Views/Books/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

Demo.Web/Views/Demo/Index.cshtml
@model Demo.Web.Models.Demo.IndexModel
@{
    ViewData["Title"] = "Index";
}

@using (Html.BeginForm("Index", "Demo", FormMethod.Post, new { @class = "form-style" }))
{
    <h1>Test Form</h1>
    <hr />
    <div class="form-group">
        @Html.LabelFor(model => model.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Password, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ConfirmPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" class="btn btn-primary" value="Submit" />
        </div>
    </div>
}
<hr />

<form asp-controller="Demo" asp-action="Index" method="post" class="form-horizontal">
    <h1>Tag helper approach</h1>
    <hr />
    <div class="form-group">
        <label asp-for="Email" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Email" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Password" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Password" type="password" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <label asp-for="ConfirmPassword" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="ConfirmPassword" type="password" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" class="btn btn-primary" value="Submit" />
        </div>
    </div>
</form>

Demo.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<link href="~/scss/demo.css" rel="stylesheet" />
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Demo.Web/Views/Shared/_PublicLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Demo</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Demo.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Demo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Demo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>